# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('m1', models.BooleanField()),
                ('m2', models.BooleanField()),
                ('m3', models.NullBooleanField()),
                ('m4', models.BooleanField()),
                ('m5', models.BooleanField()),
                ('comments', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDRC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('m1_score', models.IntegerField(default=0)),
                ('m2_score', models.IntegerField(default=0)),
                ('m3_score', models.IntegerField(default=0)),
                ('m4_score', models.IntegerField(default=0)),
                ('m5_score', models.IntegerField(default=0)),
                ('HW_Assigned', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=16)),
                ('m1_name', models.CharField(default='Appropriate Behavior', max_length=40)),
                ('m2_name', models.CharField(default='Attentive', max_length=40)),
                ('m3_name', models.CharField(default='Homework', max_length=40)),
                ('m4_name', models.CharField(default='Needed redirection and reminders', max_length=40)),
                ('m5_name', models.CharField(default='Organized', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=16)),
                ('email', models.EmailField(default='empty@gmail.com', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='Reports.Teacher'),
        ),
        migrations.AddField(
            model_name='masterdrc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Student'),
        ),
        migrations.AddField(
            model_name='drc',
            name='masterDRC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.MasterDRC'),
        ),
        migrations.AddField(
            model_name='drc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Student'),
        ),
        migrations.AddField(
            model_name='drc',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Teacher'),
        ),
    ]
