# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drc',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterdrc',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
