# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_auto_20180221_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=16)),
                ('email', models.EmailField(default='empty@gmail.com', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reports.Student')),
            ],
        ),
    ]
