# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='type',
            field=models.CharField(default='Parent', max_length=16),
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(default='Teacher', max_length=16),
        ),
    ]
